CREATE SCHEMA images;

CREATE TABLE images.images (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uri text NOT NULL,
    created_at timestamptz DEFAULT now()
);

CREATE TABLE images.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id bigint UNIQUE NOT NULL,
    created_at timestamptz DEFAULT now()
);

CREATE TABLE images.user_interactions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_id bigint NOT NULL REFERENCES images.images (id),
    user_id bigint NOT NULL REFERENCES images.users (chat_id),
    react int,
    UNIQUE (image_id, user_id),
    created_at timestamptz DEFAULT now()
);

CREATE INDEX ON images.user_interactions (image_id, user_id);

